---
output: rmarkdown::github_document
#bibliography: README-refs.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# R/`shifttx`

> ...

---

## What's `shifttx`?

`shifttx` is an R package that ...

---

## Installation

Install the most recent _stable release_ from GitHub via
[`devtools`](https://www.rstudio.com/products/rpackages/devtools/):

```{r gh-master-installation, eval = FALSE}
devtools::install_github("nhejazi/shifttx")
```

---

<!--
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
## basic example code
```
-->

## Issues

If you encounter any bugs or have any specific feature requests, please [file an
issue](https://github.com/nhejazi/shifttx/issues).

---

## License

&copy; 2017 [Nima S. Hejazi](http://nimahejazi.org) and [David C.
Benkeser]()

The contents of this repository are distributed under the MIT license. See file
`LICENSE` for details.

