---
title: "Basic Simulations for Targeted Learning with Stochastic Treatment Regimes"
author: "Nima Hejazi and David Benkeser"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
---

```{r rmd_setup, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
library(here)
library(sl3)
library(condensier)
library(shifttx)
```

```{r sim_args}
library(future)
library(doFuture)
registerDoFuture()

# parameters for simulating simple data for tmle-shift sketch
n_w <- 1
a1_mean <- 2
a0_mean <- 0
sim_truth <- 2

# meta-parameters for controlling simulation type
sim_results_cat <- NULL
seed_int <- 94611288
n_sim <- 1e3
n_obs <- c(50, 250, 1000)
Q_fit_type <- c("glm", "sl")
```

```{r run_sim, message = FALSE}
# simulation
for (fit_type in Q_fit_type) {
  for (samp in n_obs) {
    sim_results <- foreach(i = seq_len(n_sim), .combine = rbind) %dopar% {

      # set the seed properly for multicore parallelization
      set.seed(seed_int + i)
    
      if ((i %% 10) == 0) {
        print(paste("Starting simulation", i, "/", n_sim, "for sample size",
                    n_obs, "with TMLE type of", fit_type))
      }
    
      ## baseline covariate -- simple, binary
      W <- as.numeric(replicate(n_w, rbinom(samp, 1, 0.5)))
    
      ## set and organize treatment based on baseline W
      A1 <- rnorm(length(which(W == 1)), mean = a1_mean, sd = 1)
      A0 <- rnorm(length(which(W == 0)), mean = a0_mean, sd = 1)
      A <- rep(NA, samp)
      A[which(W == 0)] <- A0
      A[which(W == 1)] <- A1
    
      # create outcome
      Y <- A + W + rnorm(samp)
    
      # do a TMLE
      tmle_shift <- tmle_shifttx(W = W,
                                 A = A,
                                 Y = Y,
                                 delta = 0.5,
                                 g_fit_args = list(nbins = 20,
                                                   bin_method = "dhist",
                                                   bin_estimator =
                                                     speedglmR6$new(),
                                                   parfit = FALSE),
                                 Q_fit_args = list(fit_method = fit_type,
                                                   glm_formula = "Y ~ .",
                                                   sl_learners = c("mean",
                                                                   "glm_fast"),
                                                   sl_metalearner = "nnls"),
                                 fluc_method = "standard",
                                 eif_tol = 1e-7
                                )
      ci_shift <- confint(tmle_shift)
    
      # summary statistics from TMLE procedure
      point_est <- tmle_shift$psi
      ci_in <- as.numeric(between(sim_truth, ci_shift[1], ci_shift[3]))
      sim_iter_out <- c(point_est, ci_in)
    }

    # compute average estimate, bias, and sd across simulations
    sim_results <- as.data.frame(sim_results)
    colnames(sim_results) <- c("est", "ci_ind")
    sim_point_est <- mean(sim_results$est)
    sim_est_var <- var(sim_results$est)
    sim_est_bias <- sim_point_est - sim_truth
    sim_est_cover <- sum(sim_results$ci_in) / n_sim
    sim_results_out <- as.data.frame(cbind(samp, sim_point_est, sim_est_var,
                                           sim_est_bias, sim_est_cover,
                                           fit_type))
    colnames(sim_results_out) <- c("size", "estimate", "variance", "bias",
                                   "coverage", "tmle_type")
    sim_results_cat <- rbind(sim_results_cat, sim_results_out)
  }
}
sim_results_cat
```

