TITLE = basic_sim

glm_sim:
	Rscript -e "rmarkdown::render('$(TITLE)_glm.Rmd')"

sl_sim:
	Rscript -e "rmarkdown::render('$(TITLE)_sl.Rmd')"

dens:
	Rscript -e "rmarkdown::render('condensier_weights.Rmd')"

