#' Compute Augmented Inverse Probability Weighted Estimate of Counterfactual
#' Mean Under Shifted Treatment
#'
#' @param data_internal A \code{data.table} constructed internally by a call to
#'  \code{txshift}. This contains most of the data elements needed for computing
#'  the one-step estimator.
#' @param C A \code{numeric} binary vector giving information on whether a given
#'  observation was subject to censoring. This is used to compute an IPCW-AIPW
#'  estimator in cases where two-stage sampling is performed. Default assumes no
#'  censoring was present (i.e., a two-stage design was NOT used). N.B., this is
#'  equivalent to the term %\Delta in the notation used in the original Rose and
#'  van der Laan manuscript that introduced/formulated IPCW-AIPW estimators.
#' @param V The covariates that are used in determining the sampling procedure
#'  that gives rise to censoring. The default is \code{NULL} and corresponds to
#'  scenarios in which there is no censoring (in which case all values in the
#'  preceding argument \code{C} must be uniquely 1. To specify this, pass in a
#'  NAMED \code{list} identifying variables amongst W, A, Y that are thought to
#'  have played a role in defining the sampling/censoring mechanism (C).
#' @param delta A \code{numeric} value indicating the shift in the treatment to
#'  be used in defining the target parameter. This is defined with respect to
#'  the scale of the treatment (A).
#' @param cens_weights A \code{numeric} vector that gives inverse probability of
#'  censoring weights for each observation. These are generated by invoking the
#'  routines for estimating the censoring mechanism.
#' @param cens_weights_norm A normalized version of the preceding argument
#'  \code{cens_weights}, wherein the weights are scaled such that they sum to
#'  the unit value.
#' @param ipcw_estim An object providing the value of the censoring mechanism
#'  evaluated across the full data. This object is passed in after being
#'  constructed by a call to the internal function \code{est_ipcw}.
#' @param Qn_estim An object providing the value of the outcome evaluated after
#'  imposing a shift in the treatment. This object is passed in after being
#'  constructed by a call to the internal function \code{est_Q}.
#' @param Hn_estim An object providing values of the auxiliary ("clever")
#'  covariate, constructed from the treatment mechanism and required for
#'  targeted minimum loss-based estimation. This object object should be passed
#'  in after being constructed by a call to the internal function \code{est_Hn}.
#' @param eif_tol A \code{numeric} giving the convergence criterion for the AIPW
#'  estimator. This is the the maximum mean of the efficient influence function
#'  (EIF) to be used in declaring convergence (theoretically, should be zero).
#' @param eif_reg_type Whether a flexible nonparametric function ought to be
#'  used in the dimension-reduced nuisance regression of the targeting step for
#'  the censored data case. By default, the method used is a nonparametric
#'  regression based on the Highly Adaptive Lasso (from package \code{hal9001}).
#'  Set this to \code{"glm"} to instead use a simple linear regression model.
#'  In this step, the efficient influence function (EIF) is regressed against
#'  covariates contributing to the censoring mechanism (i.e., EIF ~ V | C = 1).
#' @param ipcw_fit_args A \code{list} of arguments, all but one of which are
#'  passed to \code{est_ipcw}. For details, please consult the documentation for
#'  \code{est_ipcw}. The first element of this (i.e., \code{fit_type}) is used
#'  to determine how this regression is fit: "glm" for generalized linear model,
#'  "sl" for a Super Learner, and "fit_spec" a user-specified input of the form
#'  produced by \code{est_ipcw}. NOTE THAT this first argument is not passed to
#'  \code{est_ipcw}.
#' @param ipcw_fit_type A \code{character} providing the type of regression to
#'  be fit in estimating the relationship between the variables composing the
#'  censoring mechanism and the efficient influence function. Choose "glm" for
#'  generalized linear models or "sl" for use of the Super Learner algorithm. If
#'  selecting the latter, the final argument \code{sl_lrnrs} must be provided.
#' @param ipcw_efficiency Whether to invoke an augmentation of the IPCW-AIPW
#'  estimation procedure that performs an iterative process to ensure efficiency
#'  of the resulting estimate. The default is \code{TRUE}; only set to
#'  \code{FALSE} if possible inefficiency of the IPCW-AIPW is not a concern.
#'
#' @importFrom data.table as.data.table setnames
#' @importFrom stringr str_detect
#' @importFrom dplyr filter select "%>%"
#' @importFrom Rdpack reprompt
#'
#' @return S3 object of class \code{txshift} containing the results of the
#'  procedure to compute a AIPW estimate of the treatment shift parameter.
#'
#' @export
onestep_txshift <- function(data_internal,
                            C = rep(1, nrow(data_internal)),
                            V = NULL,
                            delta,
                            cens_weights,
                            cens_weights_norm,
                            ipcw_estim,
                            Qn_estim,
                            Hn_estim,
                            eif_tol = 1 / nrow(data_internal),
                            eif_reg_type = c("hal", "glm"),
                            ipcw_fit_args,
                            ipcw_fit_type,
                            ipcw_efficiency = TRUE) {

  # invoke efficient IPCW-AIPW, per Rose & van der Laan (2011), if necessary
  if (ipcw_efficiency & !all(C == 1) & !is.null(V) & !is.null(ipcw_estim)) {
    # normalize censoring mechanism weights (to be overwritten)
    cens_weights <- C / ipcw_estim$pi_mech
    cens_weights_norm <- cens_weights / sum(cens_weights)

    # quantities to be updated in iterative procedure (to be overwritten)
    pi_mech_star <- ipcw_estim$pi_mech
    Qn_estim_updated <- Qn_estim

    # update sub-model fluctuation, re-compute EIF, and update EIF
    os_ipcw_eif_out <- ipcw_eif_update(
      data_in = data_internal,
      C = C,
      V = V,
      ipc_mech = pi_mech_star,
      ipc_weights = cens_weights,
      ipc_weights_norm = cens_weights_norm,
      Qn_estim = Qn_estim_updated,
      Hn_estim = Hn_estim,
      estimator = "onestep",
      fit_type = ipcw_fit_type,
      eif_tol = eif_tol,
      sl_lrnrs = ipcw_fit_args$sl_lrnrs,
      eif_reg_type = eif_reg_type
    )

    # overwrite and update quantities to be used in the next iteration
    Qn_estim_updated <- data.table::as.data.table(
      list(
        # NOTE: need to re-scale estimated outcomes values within bounds of Y
        scale_to_unit(
          vals = os_ipcw_eif_out$Qn_estim$noshift
        ),
        scale_to_unit(
          vals = os_ipcw_eif_out$Qn_estim$upshift
        )
      )
    )
    data.table::setnames(Qn_estim_updated, names(Qn_estim))
    cens_weights <- os_ipcw_eif_out$ipc_weights
    cens_weights_norm <- os_ipcw_eif_out$ipc_weights_norm
    pi_mech_star <- os_ipcw_eif_out$pi_mech_star

    # compute updated mean of efficient influence function
    eif_ipcw <- os_ipcw_eif_out$eif_eval$eif - os_ipcw_eif_out$ipcw_eif
    eif_ipcw_var <- var(eif_ipcw) / length(C)

    # update the one-step estimator with mean of the 2nd half of augmented EIF
    # NOTE: the 2nd half of the EIF is actually a correction (with a minus sign
    #       in front of it) so the mean ought to be subtracted, not added
    psi_onestep <- os_ipcw_eif_out$eif_eval$psi - mean(os_ipcw_eif_out$ipcw_eif)
    conv_results <- list(psi_onestep, eif_ipcw_var, mean(eif_ipcw)) %>%
      as.matrix() %>%
      t() %>%
      data.table::as.data.table()
    data.table::setnames(conv_results, c("psi", "var", "eif_mean"))

    # create output object
    txshift_out <- unlist(
      list(
        call = call,
        os_ipcw_eif_out$eif_eval,
        n_iter = 0,
        estimator = "onestep",
        outcome = list(data_internal$Y)
      ),
      recursive = FALSE
    )

    # manually update output object with one-step results
    txshift_out[["psi"]] <- psi_onestep
    txshift_out[["var"]] <- eif_ipcw_var
    txshift_out[["eif"]] <- eif_ipcw

    # standard one-step of the shift parameter / inefficient IPCW-AIPW estimator
  } else {
    # compute one-step estimate and EIF for the treatment shift parameter
    os_eif_out <- eif(
      Y = data_internal$Y,
      Qn = Qn_estim,
      Hn = Hn_estim,
      estimator = "onestep",
      Delta = C,
      ipc_weights = cens_weights,
      ipc_weights_norm = cens_weights_norm,
      eif_tol = eif_tol
    )

    # create output object
    txshift_out <- unlist(
      list(
        call = call,
        os_eif_out,
        n_iter = 0,
        estimator = "onestep",
        outcome = list(data_internal$Y)
      ),
      recursive = FALSE
    )
  }

  # S3-ify and return output object
  class(txshift_out) <- "txshift"
  return(txshift_out)
}
