#' Compute IPC-Weighted Component of Efficient Influence Function
#'
#' Computes an additional component of the efficient influence function needed
#' for efficient estimation of IPCW-TMLEs. This takes the form:
#' %0=P_n(\Delta-\Pi_n^*(V)))\frac{\E(D^F(P^0_{X,n})\mid\Delta=1,V)}{\Pi^*_n(V)}
#'
#' @param fluc_mod_out An object giving values of the logistic regression fit to
#'  traverse the submodel for targeted minimum loss-based estimation. This type
#'  of object should be the output of the internal routines to perform this
#'  step of the TMLE computation, as given by \code{fit_fluc}.
#' @param data_in A \code{data.frame} or similar object containing the observed
#'  data structure as produced by early steps of \code{tmle_txshift}.
#' @param Hn An object providing values of the auxiliary ("clever") covariate,
#'  constructed from the treatment mechanism and required for targeted minimum
#'  loss-based estimation. This object object should be passed in after being
#'  constructed by a call to the internal function \code{est_Hn}.
#' @param Delta Indicator for missingness. Used for compatibility with the
#'  routine to compute IPCW-TML estimates.
#' @param ipc_weights A \code{numeric} vector that gives inverse probability of
#'  censoring weights for each observation. These are generated by invoking the
#'  routines for estimating the censoring mechanism.
#' @param ipc_weights_norm A \code{numeric} vector of the same weights described
#'  in the previous argument, except normalized in this case.
#' @param eif_tol A \code{numeric} giving the minimum value of the tolerance to
#'  be used in evaluating whether the computation of the efficient influence
#'  function has converged.
#'
#' @importFrom stats var
#' @importFrom dplyr if_else add_count select mutate
#'
#' @keywords internal
#'
#' @export
#'
#' @author Nima Hejazi
#' @author David Benkeser
#
tmle_eif_ipcw <- function(fluc_mod_out,
                          data_in,
                          Hn,
                          Delta,
                          ipc_weights = rep(1, nrow(data_in)),
                          ipc_weights_norm = rep(1, nrow(data_in)),
                          eif_tol = 1e-10) {

  # compute TMLE of the treatment shift parameter
  param_obs_est <- rep(0, length(Delta))
  param_obs_est[Delta == 1] <- ipc_weights_norm * fluc_mod_out$Qn_shift_star
  psi <- sum(param_obs_est)

  # compute the efficient influence function (EIF) / canonical gradient (D*)
  eif <- rep(0, length(Delta))
  eif[Delta == 1] <- ipc_weights * (Hn$noshift *
    (data_in$Y - fluc_mod_out$Qn_noshift_star) +
    (fluc_mod_out$Qn_shift_star - psi))

  # sanity check on EIF
  # NOTE: EIF ~ N(0, V(D(P)(o))), so mean(EIF) ~= 0
  eif_msg <- dplyr::if_else(
    abs(mean(eif)) < eif_tol,
    paste("EIF mean <", eif_tol, "(sufficiently low)."),
    paste(
      "EIF mean =", mean(eif),
      "(higher than expected)."
    )
  )

  # compute the variance based on the EIF and scale by number of observations
  # var_eif <- mean(eif^2) / length(Delta)  <= denom since we use full N
  var_eif <- stats::var(eif) / length(Delta)

  # return the variance and the EIF value at each observation
  out <- list(psi = psi, var = var_eif, eif = eif, msg = eif_msg)
  return(out)
}
